package com.gurkha.hr.domain.userDetail.ui

import com.gurkha.hr.components.date.DateData

data class EditProfileUI(
    val email: String = "",
    val phoneNumber: String = "",
    val imageUrl: String = "",
    val fullName: String = "",
    val initials: String = "",
    val levelName: String = "",
    val employeeId: Int = 0,
    val branchName: String = "",
    val branchId: Int = 0,
    val levelId: Long= 0,
    val mapId: Int = 0,
    val joinedDate: DateData,
    val address: String = "",
    val dateOfBirth: DateData,
    val gender: String = "",
    val nationality: String = "",
    val maritalStatus: String = "",
    val guardianName: String = "",
    val guardianPhone: String = "",
    val isCompleteProfile: String = "",
    val bloodGroup: String = "",
    val designation: String = "",
    val employeeTypes: String = "",
    val panNumber: String = "",
    val pfNumber: String = "",
    val bachelorImage: String = "",
    val citizenshipBackImage: String = "",
    val citizenshipFrontImage: String = "",
    val departmentId: Int = 0,
    val designationId: Int = 0,
    val enableImageAttendance: String = "",
    val enableManualAttendance: String = "",
    val experienceDocuments: String = "",
    val masterImage: String = "",
    val nationalId: String = "",
    val panImage: String = "",
    val password: String = "",
    val plusTwoImage: String = "",
    val profileId: Int = 0,
    val slcDocument: String = "",
    val userProfileUrl: String = ""
)
