package com.gurkha.hr.domain.userDetail.model

data class UserDetailData(
    val address: String,
    val bachelorImage: String?,
    val bloodGroup: String,
    val branchId: Int,
    val employeeId: Int,
    val branchName: String,
    val citizenshipBackImage: String?,
    val citizenshipFrontImage: String?,
    val dateOfBirth: String,
    val departmentId: Int,
    val designation: String,
    val designationId: Int,
    val email: String,
    val employeeType: String,
    val enableImageAttendance: String,
    val enableManualAttendance: String,
    val experienceDocuments: String?,
    val fullName: String,
    val gender: String,
    val guardianName: String,
    val guardianNumber: String,
    val imageUrl: String?,
    val joinedDate: String,
    val levelName: String,
    val levelId: Long,
    val mapId: Int?,
    val maritalStatus: String,
    val masterImage: String?,
    val nationalId: String?,
    val panImage: String?,
    val panNumber: String,
    val password: String,
    val pfNumber: String,
    val phoneNumber: String,
    val plusTwoImage: String?,
    val profileId: Int,
    val slcDocument: String?,
    val userProfileUrl: String,
    val nationality: String,
    val initials: String,
    val isCompleteProfile: Boolean,

)