package com.gurkha.model.user_data

import kotlinx.serialization.Serializable

@Serializable
data class UserData(
    val email: String = "",
    val phoneNumber: String = "",
    val imageUrl: String? =null,
    val fullName: String = "",
    val initials: String = "",
    val levelName: String = "",
    val employeeId: Int = 0,
    val branchName: String = "",
    val branchId: Int = 0,
    val levelId: Long= 0,
    val mapId: Int = 0,
    val joinedDate: String = "",
    val address: String = "",
    val dateOfBirth: String = "",
    val gender: String = "",
    val nationality: String = "",
    val maritalStatus: String = "",
    val guardianName: String = "",
    val guardianPhone: String = "",
    val isCompleteProfile: Boolean = false ,
    val bloodGroup: String = "",
    val designation: String = "",
    val employeeTypes: String = "",
    val panNumber: String = "",
    val pfNumber: String = "",
    val bachelorImage: String? = null,
    val citizenshipBackImage: String? = null,
    val citizenshipFrontImage: String? = null,
    val departmentId: Int = 0,
    val designationId: Int = 0,
    val enableImageAttendance: String = "",
    val enableManualAttendance: String = "",
    val experienceDocuments: String? = null,
    val masterImage: String? = null,
    val nationalId: String? = null,
    val panImage: String ?= null,
    val password: String = "",
    val plusTwoImage: String? = null,
    val profileId: Int = 0,
    val slcDocument: String? = null,
    val userProfileUrl: String? = null,
    val roles : List<String>? = null
)