package com.gurkha.hr.domain.userDetail.mapper

import com.gurkha.hr.components.extractInitials
import com.gurkha.hr.domain.userDetail.model.UserDetailData
import com.gurkha.hr.domain.userDetail.ui.EditProfileUI
import com.gurkha.model.userDetail.UserDetailResponseDto
import com.gurkha.model.user_data.UserData

fun UserDetailResponseDto.toData(): UserDetailData {
    return UserDetailData(
        email = detail?.email ?: "",
        phoneNumber = detail?.employeeDetails?.phoneNumber ?: "",
        userProfileUrl = detail?.imageUrl ?: "",
        fullName = detail?.fullName ?: "",
        levelName = detail?.levelName ?: "",
        employeeId = detail?.employeeId ?: 0,
        address = detail?.employeeDetails?.address ?: "",
        branchName = detail?.employeeDetails?.user?.branch?.branchName ?: "",
        dateOfBirth = detail?.employeeDetails?.dateOfBirth ?: "",
        gender = detail?.employeeDetails?.gender ?: "",
        joinedDate = detail?.employeeDetails?.joinedDate ?: "",
        nationality = detail?.employeeDetails?.country ?: "",
        maritalStatus = detail?.employeeDetails?.maritalStatus ?: "",
        guardianName = detail?.employeeDetails?.guardianName ?: "",
        guardianNumber = detail?.employeeDetails?.guardianNumber ?: "",
        initials = detail?.fullName?.extractInitials() ?: "",
        isCompleteProfile = detail?.isCompleteProfile ?: ",",
        bloodGroup = detail?.employeeDetails?.bloodGroup ?: "",
        designation = detail?.designation ?: "",
        panNumber = detail?.employeeDetails?.panNumber ?: "",
        pfNumber = detail?.employeeDetails?.pfNumber ?: "",
        bachelorImage = detail?.employeeDetails?.bachelorImageUrl ?: "",
        branchId =detail?.employeeDetails?.user?.branch?.id ?: 0,
        citizenshipBackImage = detail?.employeeDetails?.citizenshipBackImage ?: "",
        citizenshipFrontImage = detail?.employeeDetails?.citizenshipFrontImage ?: "",
        departmentId = detail?.departmentId?:0,
        designationId =detail?.designationId?: 0 ,
        employeeType = detail?.employeeType ?: "",
        enableImageAttendance = detail?.employeeDetails?.enableImageAttendance ?: "",
        enableManualAttendance = detail?.employeeDetails?.enableManualAttendance ?: "",
        experienceDocuments = detail?.employeeDetails?.experienceDocumentsUrl ?: "",
        imageUrl = detail?.imageUrl ?: "",
        levelId = detail?.levelId ?: 0,
        mapId = detail?.employeeDetails?.mapId ?: 0,
        masterImage = detail?.employeeDetails?.masterImageUrl ?: "",
        nationalId = detail?.employeeDetails?.nationalIdImage ?: "",
        panImage = detail?.employeeDetails?.panImage ?: "",
        password = "",
        plusTwoImage = detail?.employeeDetails?.plusTwoImage ?: "",
        profileId = detail?.profileId ?: detail?.employeeDetails?.profileId ?: 0,
        slcDocument = detail?.employeeDetails?.slcDocumentUrl ?: ""
    )
}

fun UserData.toDetail(): UserDetailData {
    return UserDetailData(
        email = email,
        phoneNumber = phoneNumber,
        fullName = fullName,
        levelName = levelName,
        employeeId = employeeId,
        address = address,
        dateOfBirth = dateOfBirth,
        gender = gender,
        joinedDate = joinedDate,
        nationality = nationality,
        maritalStatus = maritalStatus,
        guardianName = guardianName,
        guardianNumber = guardianPhone,
        initials = initials,
        isCompleteProfile = isCompleteProfile,
        bloodGroup = bloodGroup,
        designation = designation,
        employeeType = employeeTypes,
        panNumber = panNumber,
        pfNumber = pfNumber,
        branchName = branchName,
        bachelorImage =bachelorImage ,
        branchId = branchId,
        citizenshipBackImage = citizenshipBackImage,
        citizenshipFrontImage = citizenshipFrontImage,
        departmentId = departmentId,
        designationId = designationId,
        enableImageAttendance = enableImageAttendance,
        enableManualAttendance = enableManualAttendance,
        experienceDocuments = experienceDocuments,
        imageUrl = imageUrl,
        levelId = levelId,
        mapId = mapId,
        masterImage =masterImage,
        nationalId = nationalId,
        panImage = panImage,
        password = password,
        plusTwoImage = plusTwoImage,
        profileId =  profileId,
        slcDocument = slcDocument,
        userProfileUrl = userProfileUrl,
    )
}

fun UserDetailData.toUI(): EditProfileUI{
    return EditProfileUI(
        fullName = fullName,
        email = email,
        levelName = levelName,
        phoneNumber = phoneNumber,
        employeeId = employeeId,
        branchName = branchName,
        address = address,
        joinedDate = joinedDate,
        maritalStatus = maritalStatus,
        gender = gender,
        dateOfBirth = dateOfBirth,
        bloodGroup = bloodGroup,
        guardianName = guardianName,
        guardianPhone = guardianNumber,
        designation = designation,
        employeeTypes = employeeType,
        panNumber = panNumber,
        pfNumber = pfNumber

    )
}

fun EditProfileUI.toDomain(): UserDetailData {
    return UserDetailData(
        email = email,
        phoneNumber = phoneNumber,
        fullName = fullName,
        levelName = levelName,
        employeeId = employeeId,
        address = address,
        dateOfBirth = dateOfBirth,
        gender = gender,
        joinedDate = joinedDate,
        nationality = nationality,
        maritalStatus = maritalStatus,
        guardianName = guardianName,
        guardianNumber = guardianPhone,
        initials = initials,
        isCompleteProfile = isCompleteProfile,
        bloodGroup = bloodGroup,
        designation = designation,
        employeeType = employeeTypes,
        panNumber = panNumber,
        pfNumber = pfNumber,
        branchName = branchName,
        bachelorImage =bachelorImage ,
        branchId = branchId,
        citizenshipBackImage = citizenshipBackImage,
        citizenshipFrontImage = citizenshipFrontImage,
        departmentId = departmentId,
        designationId = designationId,
        enableImageAttendance = enableImageAttendance,
        enableManualAttendance = enableManualAttendance,
        experienceDocuments = experienceDocuments,
        imageUrl = imageUrl,
        levelId = levelId,
        mapId = mapId,
        masterImage =masterImage,
        nationalId = nationalId,
        panImage = panImage,
        password = password,
        plusTwoImage = plusTwoImage,
        profileId =  profileId,
        slcDocument = slcDocument,
        userProfileUrl = userProfileUrl,
    )
}
